# Generated by Django 5.0.2 on 2024-02-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doctor_id', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=100)),
                ('contact_information', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='hms',
        ),
    ]
